"""add_followers

Revision ID: 743d03add50a
Revises: 635c0975b87f
Create Date: 2017-07-24 11:16:42.298170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743d03add50a'
down_revision = '635c0975b87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follwers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follwers')
    # ### end Alembic commands ###
